
export let kiz_ismi    = ["Elif","Açelya","Elvan","Selen","Emine","Eda","Melis","Ceylin","Zeynep","Pelin","Özlem"]
export let erkek_ismi  = ["Can","Yiğit","Türkdoğan","Ferhat","Emir","Buğra","Eren","Ertuğrul","Deniz","Durmuş Kartcı","Arda","Ali","Burak","Sidar","Ömer","Emin Kartcı"]
export let sehirler    = ['Adana', 'Adıyaman', 'Afyon', 'Ağrı', 'Amasya', 'Ankara', 'Antalya', 'Artvin', 'Aydın', 'Balıkesir', 'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Çanakkale', 'Çankırı', 'Çorum', 'Denizli', 'Diyarbakır', 'Edirne', 'Elazığ', 'Erzincan', 'Erzurum', 'Eskişehir', 'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkari', 'Hatay', 'Isparta', 'Mersin', 'İstanbul', 'İzmir', 'Kars', 'Kastamonu', 'Kayseri', 'Kırklareli', 'Kırşehir', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya', 'Manisa', 'Kahramanmaraş', 'Mardin', 'Muğla', 'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Rize', 'Sakarya', 'Samsun', 'Siirt', 'Sinop', 'Sivas', 'Tekirdağ', 'Tokat', 'Trabzon', 'Tunceli', 'Şanlıurfa', 'Uşak', 'Van', 'Yozgat', 'Zonguldak', 'Aksaray', 'Bayburt', 'Karaman', 'Kırıkkale', 'Batman', 'Şırnak', 'Bartın', 'Ardahan', 'Iğdır', 'Yalova', 'Karabük', 'Kilis', 'Osmaniye', 'Düzce']
export let ince_isimler = ["Ahmet","Yiğit"]
export let kalin_isimler = ["Can","Ferhat"]
export let elementler = ["H","He","Li","Be","B","C","N"]
export let mitoz_evre = ["Profaz","Metafaz","Anafaz","Telofaz","Sitokinez","İnterfaz"]
export let yazim_hatali_cumle = [
"Ayşe Teyzem geldi.",
"Yarına Dünyalar kadar ödevim var.",
"İngiliz Anahtarı aldık.",
"Hoca testleri 2'şer 2'şer dağıttı.",
"Geldinmi?",
"Ülkemizin ki kadar alana sahip değil.",
"12'inci yıldönümünü kutladılar.",
"Cumhuriyet, 29 Ekim 1923'de kuruldu.",
"Kendisine 2’inci Aristo denirdi.",
"Zaferin 70'nci yılı kutlandı.",
"Vergi afıyla borçlarından kurtuldu.",
"Ahmet Amcam, bekçi Hüseyin'e olanları anlattı.",
"Bu soruyu tam olarak anlıyamamış.",
"Başak apartmanı, ünlülerin buluşma mekanıydı.",
"Size arzedip çıkacağım.",
"Art arda yaşadığımız sıkıntılar, doğruyla yanlışı ayırtetmemizi sağladı.",
"Ayşe’de geldi.",
"Çocukken gittiğim Uzungöl Beldesi, unutamadığım yerlerdendir.",
"Turgutlu belediyesine gittim.",
"Sanat, bir takım değerler içerir.",
"Dilimizin 1960'lardan buyana hangi aşamalardan geçtiği araştırılıyor.",
"Her Cuma tören yapılıyor.",
"Çağırılmadığı için akşamki davette o yoktu.",
"Çiçekcinin yeni açtığı dükkân çok iyi çalışıyor.",
"Anlaşma metnine her iki tarafta sadık kaldı.",
"Camlarında buzdan yapıldığını sanır.",
"Kimi zamanda tanıyamazdı.",
"Gidip te gelmemek var.",
"Sıkıntılı günlerim de arkadaşlarıma giderim.",
"Yapılan ölçümler hava koşullarına bağlı olarak değişgenlik gösteriyormuş.",
"Yeni deniz altılar alınacakmış.",
"Meşale Dergisini çıkaranlar epey gençti.",
"Türkiye Sakatlar derneği etkinlik yaptı.",
"Dükkanını başkasına devir etti.",
"Bu kitap Türk Dili'nin ilk sözlüğüdür.",
"Elattığı her konuda yanıldı.",
"Geleneklerimizi ve Anadolu Estetiğini de yüzeye çıkarmayı başarmıştır.",
"Okullar genellikle Eylülün ikinci haftasında öğretime başlar.",
"Tevfik Fikret'de bu özelliği görürüz.",
"Buraya yeni bir yaya geçiti yapılacak.",
"Törende çok mutlu olmuş, göğüsü kabarmıştı.",
"Gördümüydü dayanamaz.",
"Git bu mevsimde grup vakti Cihangir'den bak.",
"Türkiye'nin Güneyi genellikle yağışlıdır.",
"25 Haziran Salı Günü yapılacak.",
"Arkadaşımız bu cezayı haketmemişti.",
"Hasan'lar bize gelmek istiyormuş.",
"25 Haziranda başlayacak.",
"Bunca yıl çalıştıktan sonra öğretmenliği bırakmak hiçte kolay değildi.",
"Ona isnad edilen suçlerı reddetti."
]
export let yazim_hatasiz_cumle = [
"Mehmet amcam dün gitti.",
"Hoca dünyalar kadar ödev verdi",
"En sevdiğim baklagil Antep fıstığıdır.",
"Oturaklar üçer üçer dizilmişti.",
"Dün meydanda gezen sen miydin?",
"Sende beni etkileyen bir şey var.",
"Az ötede duran arabayı gördünüz mü?",
"Monte Carlo’da geçen sene tanışmıştık.",
"Gemide yolculuk yapmak en büyük zevkiydi.",
"Çocukken çocuk olmaktan çok sıkılırdım.",
"Sokaklarda oynarken eve dönüş vaktimin hatırlatılmasından hoşlanmam.",
"Eski bir çocuk romanını anlatmak için kıvranıyorum.",
"Bir anda onun gibi davrandığınızı fark eder.",
"Gençliğin bizi nasıl eğip büktüğünü anlatıyor.",
"Bir çocuğun hissettiği çaresizlik ezdi beni.",
"Kendini unutan bir çocuğun hissettiği çaresizlik sarstı beni.",
"Nemeçek’le birlikte boş sokaklarda koşturduk.",
"Senden hiçbir şey istemiyorum.",
"Yüzyılımızın önemli bilim adamlarındandır.",
"Kızartmanın üstüne yoğurt koymayı severim.",
"Sen az önce hayata dikiz aynasından bakıyordun.",
"Bundan sonra sana bir gıdım yok.",
"Beyaz yakalılar köy çocuklarını muayene etti.",
"Beslenme alışkanlığımız kontrol etmeliyiz.",
"O küçük ayaklı, çelimsiz çocuğu düşünüyorum.",
"Sendeki bu değişikliğin sebebi ne acaba?",
"Odadaki lambayı hemen kapatalım.",
"Askıdaki çantada ne kadar para var?",
"Bilmiyorum ki cevaplayayım.",
"Araba gürültüsünden başınız mı şişti?",
"Bu saatte eve gelinmeyeceğini bilmiyor musun?",
"Günde iki litre su içmenin gerekliliğini bilmiyor muydun?",
"Eskiyen pantolonunu terziye verdin miydi?",
"Bu ay maalesef et alamayacağız.",
"Dünyanın bütün çocukları onun romanıyla büyüyecek.",
"Yazamamaktan mı, unutulmaktan mı korkuyorsun?",
"Arkadaşlarımın hoşuna gitsin diye devam ettim.",
"Bizim kaloriferin peteği hep bozuluyor.",
"Zavallı genç, kıza sırılsıklam aşık olmuştu.",
"Her yaz kızılcık reçeli şerbeti yaparız.",
"Devenin hörgücü ne işe yarar, biliyor musun?",
"Ona verdiğim çantayı hoyratça kullanmış.",
"Bu seneki karpuzlar nedense gömgök.",
"Kütahya’da hediye edilen seramik vazo param parça oldu.",
"Bir de utanmadan bana yalan söylüyorsun.",
"Hasta çocuğun yüzü sapsarıydı.",
"Fıkrayı ona anlatınca büsbütün iştahı kaçtı.",
"Yemek yapmaya başlayalım mı?",
"Lakin vatandan ayrılışın ıstırabı zor.",
"İşler senin zannettiğin gibi yürümüyor.",
]
export let noktalama_hatali_cumle = ["Ayşe Teyzem geldi.","Yarına Dünyalar kadar ödevim var.","İngiliz Anahtarı aldık.","Hoca testleri 2'şer 2'şer dağıttı.","Geldinmi?"]
export let noktalama_hatasiz_cumle = ["Ayşe Teyzem geldi.","Yarına Dünyalar kadar ödevim var.","İngiliz Anahtarı aldık.","Hoca testleri 2'şer 2'şer dağıttı.","Geldinmi?"]


export let katli_oranlar_uygulanabilir_bilesikleri = ["C"+"2".sub()+"O-C"+"2".sub()+"O"+"2".sub(),"N"+"2".sub()+"H-N"+"2".sub()+"H"+"2".sub(),"Al"+"2".sub()+"Na-Al"+"2".sub()+"Na"+"2".sub(),"H"+"2".sub()+"He-H"+"2".sub()+"He"+"2".sub(),"Fe"+"2".sub()+"O-Fe"+"2".sub()+"O"+"2".sub()]