"use strict";
exports.__esModule = true;
exports.katli_oranlar_uygulanabilir_bilesikleri = exports.yazim_hatasiz_cumle = exports.yazim_hatali_cumle = exports.mitoz_evre = exports.elementler = exports.kalin_isimler = exports.ince_isimler = exports.sehirler = exports.erkek_ismi = exports.kiz_ismi = void 0;
exports.kiz_ismi = ["Elif", "Açelya", "Elvan", "Selen", "Emin", "Eda", "Melis", "Ceylin", "Zeynep", "Pelin", "Özlem"];
exports.erkek_ismi = ["Can", "Yiğit", "Türkdoğan", "Ferhat", "Emir", "Buğra", "Eren", "Ertuğrul", "Deniz", "Durmuş", "Arda", "Ali", "Burak", "Sidar", "Ömer"];
exports.sehirler = ['Adana', 'Adıyaman', 'Afyon', 'Ağrı', 'Amasya', 'Ankara', 'Antalya', 'Artvin', 'Aydın', 'Balıkesir', 'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Çanakkale', 'Çankırı', 'Çorum', 'Denizli', 'Diyarbakır', 'Edirne', 'Elazığ', 'Erzincan', 'Erzurum', 'Eskişehir', 'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkari', 'Hatay', 'Isparta', 'Mersin', 'İstanbul', 'İzmir', 'Kars', 'Kastamonu', 'Kayseri', 'Kırklareli', 'Kırşehir', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya', 'Manisa', 'Kahramanmaraş', 'Mardin', 'Muğla', 'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Rize', 'Sakarya', 'Samsun', 'Siirt', 'Sinop', 'Sivas', 'Tekirdağ', 'Tokat', 'Trabzon', 'Tunceli', 'Şanlıurfa', 'Uşak', 'Van', 'Yozgat', 'Zonguldak', 'Aksaray', 'Bayburt', 'Karaman', 'Kırıkkale', 'Batman', 'Şırnak', 'Bartın', 'Ardahan', 'Iğdır', 'Yalova', 'Karabük', 'Kilis', 'Osmaniye', 'Düzce'];
exports.ince_isimler = ["Ahmet", "Yiğit"];
exports.kalin_isimler = ["Can", "Ferhat"];
exports.elementler = ["H", "He", "Li", "Be", "B", "C", "N"];
exports.mitoz_evre = ["Profaz", "Metafaz", "Anafaz", "Telofaz", "Sitokinez", "İnterfaz"];
exports.yazim_hatali_cumle = ["Ayşe Teyzem geldi.", "Yarına Dünyalar kadar ödevim var.", "İngiliz Anahtarı aldık.", "Hoca testleri 2'şer 2'şer dağıttı.", "Geldinmi?"];
exports.yazim_hatasiz_cumle = ["Mehmet amcam dün gitti.", "Hoca dünyalar kadar ödev verdi", "En sevdiğim baklagil Antep fıstığıdır.", "Oturaklar üçer üçer dizilmişti.", "Dün meydanda gezen sen miydin?"];
exports.katli_oranlar_uygulanabilir_bilesikleri = ["C" + "2".sub() + "O-C" + "2".sub() + "O" + "2".sub(), "N" + "2".sub() + "H-N" + "2".sub() + "H" + "2".sub(), "Al" + "2".sub() + "Na-Al" + "2".sub() + "Na" + "2".sub(), "H" + "2".sub() + "He-H" + "2".sub() + "He" + "2".sub(), "Fe" + "2".sub() + "O-Fe" + "2".sub() + "O" + "2".sub()];
